name: Production
on:
  push:
    tags: ['*']

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GCR_SA_KEY }}
          registry: asia.gcr.io

      - uses: ./.github/actions/docker-build-deploy
        with:
          deploy_phase: production
          docker_registry: asia.gcr.io/${{ secrets.GCR_PROJECT_ID }}
          docker_build_options: --build-arg BUILD_COMMAND=build
          trigger_token: ${{ secrets.ITERING_DEPLOYMENT_TRIGGER_TOKEN }}
          trigger_endpoint: ${{ secrets.ITERING_DEPLOYMENT_TRIGGER_ENDPOINT }}
