name: Staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'

      - name: Install deps
        run: go mod download

      - name: Build binary
        run: go build -o ./token

      - uses: benjlevesque/short-sha@v1.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
 
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: quay.io/darwinia-network/token-supply:sha-${{ env.SHA }}
